#!/bin/bash
#arg1: folder to clone into
#arg2 git repo
#arg3: tag/branch to checkout
function getrepo {
  if [ ! -d $1 ];
  then
    mkdir $1
  fi
  cd $1
  git pull
  if [ $? -eq 128 ];
  then
# repo doesnt exist
    git clone $2 .
  fi
  git checkout $3
}


do_browser=false;
do_opus=false;
do_vp8=false;
do_ffmpeg=false;
do_ftlsdk=false;
do_x264=false;
do_tachyon=false;

while getopts ":b" opt; do
  case $opt in
    b)
      do_browser=true;
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
INSTALL_PREFIX='/opt/tachyon'
echo "Installing Tachyon and it's dependancies to $INSTALL_PREFIX"
if [ -d "$INSTALL_PREFIX" ]; then
  echo -e "$INSTALL_PREFIX already exists.  Is it okay to completely remove this folder [Y/n]? "
  read response
  if [ $response == 'Y' ]
  then
    rm -fr $INSTALL_PREFIX
  fi
fi
mkdir -p $INSTALL_PREFIX
export PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig/:$PKG_CONFIG_PATH
cd ..
pushd .
cd ..
##################
#opus#
##################
getrepo opus https://git.xiph.org/opus.git v1.1.2
./autogen.sh
./configure --prefix=$INSTALL_PREFIX
make
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ..
#######################################
#VP8###
#######################################
getrepo libvpx https://chromium.googlesource.com/webm/libvpx v1.5.0
mkdir build-libvpx
cd    build-libvpx
../configure --prefix=$INSTALL_PREFIX --enable-shared --disable-static --disable-vp9 --disable-vp10
make
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ../..
#######################################
####ffmpeg with opus and vp8
########################################
getrepo ffmpeg https://git.ffmpeg.org/ffmpeg.git n3.0.2
./configure --enable-shared --enable-libvpx --enable-libopus --prefix=$INSTALL_PREFIX
if [ $? -ne 0 ];
then
  echo "ffmpeg configure failed, exiting"
  exit
fi
make
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ..
#######################################
#ftl-sdk
#######################################
getrepo ftl-sdk https://github.com/WatchBeam/ftl-sdk.git HEAD
mkdir build
cd build
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
if [ $? -ne 0 ];
then
  echo "cmake failure or ftl-sdk, exiting"
  exit
fi
make
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ../..

##########################
#libx264
##########################
getrepo x264 http://git.videolan.org/git/x264.git 2102de2 
./configure --enable-shared --prefix=$INSTALL_PREFIX
if [ $? -ne 0 ];
then
  echo "cmake failure or ftl-sdk, exiting"
  exit
fi
make -j$(grep -c '^processor' /proc/cpuinfo)
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ..
##########################
#Tachyon
##########################
popd
mkdir build
cd build
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
if [ $? -ne 0 ];
then
  echo "cmake failure or ftl-sdk, exiting"
  exit
fi
make -j$(grep -c '^processor' /proc/cpuinfo)
if [ $? -ne 0 ];
then
  echo "Make failed, exiting"
  exit
fi
make install
if [ $? -ne 0 ];
then
  echo "Make Install failed, exiting"
  exit
fi
cd ../.. 
##################################
# Browser
##################################
if [ $do_browser == true ]
then
  getrepo obs-qtwebkit https://github.com/bazukas/obs-qtwebkit.git HEAD
  make
  make install
  cd ..
fi

